require('nvim-treesitter.configs').setup({
  modules = {},
  auto_install = true,
  sync_install = false,
  ignore_install = {},
  ensure_installed = {
    'bash',
    'c',
    'cpp',
    'css',
    'csv',
    'fish',
    'go',
    'html',
    'ini',
    'javascript',
    'json',
    'kdl',
    'lua',
    'markdown',
    'markdown_inline',
    'nix',
    'rust',
    'toml',
    'typescript',
    'yaml',
    'zig',
  },
  highlight = { enable = true },
  incremental_selection = { enable = false },
  indent = { enable = true },

  autotag = {
    enable = true,
    enable_rename = true,
    enable_close = true,
    enable_close_on_slash = true,
  },
})
